apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jinshu
  namespace: jinshu
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
  - host: jinshu.obtstar.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jinshu-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: jinshu-backend
            port:
              number: 8080
