apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jinshu

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres-init-cm.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- infra.yaml
- ingress.yaml
- rbac.yaml
