apiVersion: v1
kind: Service
metadata:
  name: jinshu-backend
  namespace: jinshu
spec:
  selector:
    app: jinshu-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jinshu-frontend
  namespace: jinshu
spec:
  selector:
    app: jinshu-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jinshu-batch
  namespace: jinshu
  labels:
    app: jinshu-batch
spec:
  selector:
    app: jinshu-batch
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: jinshu-data-sync
  namespace: jinshu
  labels:
    app: jinshu-data-sync
spec:
  selector:
    app: jinshu-data-sync
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
