FROM node:22-slim

# Use Tsinghua mirror to speed up apt in CN environment
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list.d/debian.sources \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    chromium \
    chromium-sandbox \
    fonts-noto \
    fonts-noto-cjk \
    ghostscript \
    openjdk-17-jre-headless \
 && rm -rf /var/lib/apt/lists/*
