-- report_metadata
ALTER TABLE report_metadata ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'DRAFT';
ALTER TABLE report_metadata ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE report_metadata ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE report_metadata ADD COLUMN IF NOT EXISTS data_source_id BIGINT;

-- report_workflows
ALTER TABLE report_workflows ADD COLUMN IF NOT EXISTS operation VARCHAR(50);
ALTER TABLE report_workflows ADD COLUMN IF NOT EXISTS operator_id BIGINT;
ALTER TABLE report_workflows ADD COLUMN IF NOT EXISTS reviewed_by BIGINT;
ALTER TABLE report_workflows ADD COLUMN IF NOT EXISTS review_comment TEXT;
ALTER TABLE report_workflows ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP;
ALTER TABLE report_workflows ALTER COLUMN created_by SET DEFAULT 0;
ALTER TABLE report_workflows ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE report_workflows ALTER COLUMN updated_at DROP NOT NULL;

-- tenant
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS description TEXT;

-- task
ALTER TABLE task ADD COLUMN IF NOT EXISTS parameters TEXT;
ALTER TABLE task ALTER COLUMN type SET DEFAULT 'UNKNOWN';
ALTER TABLE task ALTER COLUMN type DROP NOT NULL;
ALTER TABLE task ADD COLUMN IF NOT EXISTS report_id BIGINT;
ALTER TABLE task ADD COLUMN IF NOT EXISTS task_type VARCHAR(50);
ALTER TABLE task ADD COLUMN IF NOT EXISTS parent_task_id BIGINT;
ALTER TABLE task ADD COLUMN IF NOT EXISTS shard_seq INTEGER;
ALTER TABLE task ADD COLUMN IF NOT EXISTS shard_total INTEGER;
ALTER TABLE task ADD COLUMN IF NOT EXISTS result TEXT;
ALTER TABLE task ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP;
ALTER TABLE task ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE task ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;
ALTER TABLE task ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE task ADD COLUMN IF NOT EXISTS started_at TIMESTAMP;
ALTER TABLE task ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;

-- audit_log
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS previous_hash VARCHAR(64);

-- users
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_fail_count INTEGER DEFAULT 0;
ALTER TABLE users ALTER COLUMN login_fail_count SET DEFAULT 0;
ALTER TABLE users ALTER COLUMN login_fail_count DROP NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR(45);
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_updated_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
-- Drop NOT NULL on existing columns that may have null data
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
